version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
      - "5173:5173"  # Add this line for Vite dev server
    depends_on:
      - mongodb
      - mysql
    networks:
      - laravel
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=bookstore.cxskoeyqyhjl.ap-south-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=bookstore
      - DB_USERNAME=admin
      - DB_PASSWORD=Logithbook543
      - MONGODB_URI=mongodb+srv://logithsivakumar07:Pwm2dvy7kYfmxF1o@bookhivecluster.sdkwik8.mongodb.net/
      - MONGODB_DB=bookstore
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data:
